 
name: Comprobar compilaci贸n del c贸digo

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  compilacion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout c贸digo
        uses: actions/checkout@v2

      - name: Instalar dependencias
        run: npm ci

      - name: Compilar c贸digo
        run: npm run build
