 
name: Análisis de código

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
   

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
