 
name: Análisis de seguridad del código

on:
  workflow_dispatch:
    

jobs:
  seguridad:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Instalar dependencias
        run: npm i

      - name: Análisis de seguridad del código
        run: npx snyk auth
