name: Deply to VPS

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  deploy:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Copy code
      run: cp -r -f . /home/cloud/app/smartest-idea-web
    - name: Install deps
      working-directory: /home/cloud/app/smartest-idea-web
      run: yarn
    - name: Build production bundle
      working-directory: /home/cloud/app/smartest-idea-web
      run: yarn build
    - name: Restart service
      working-directory: /home/cloud/app/smartest-idea-web
      run: pm2 start
