name: Deply to VPS

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  deploy:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Copy app
      run: cp -r -f . /home/cloud/app/smartest-ideas-web/
    - name: Change Directory
      run: cd /home/cloud/app/smartest-ideas-web/
    - name: Restart service
      run: pm2 start