name: Deply to VPS

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

defaults:
 run:
  working-directory: /home/cloud/app/smartest-ideas-web

jobs:
  deploy:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: yarn
    - name: Build production bundle
      run: yarn build
    - name: Restart service
      run: pm2 start
